# -------------------------------------------------------------------------------------------------------------------- #
# > How to receive events from the Bridge via SSE (Server-Sent Events) connection
# -------------------------------------------------------------------------------------------------------------------- #

GET {{sseUrl}}
hue-application-key: {{apiKey}}
Accept: text/event-stream
