openapi: 3.0.3
info:
  title: Hue CLIP API
  version: v2
  description: |
    ## Step 1
    First make sure your bridge is connected to your network and is functioning properly. Test that the official Philips Hue mobile app can control the lights on the same network.
    ## Step 2
    Then you need to discover the IP address of the bridge on your network. You can do this in a few ways.
    > NOTE – When you are ready to make a production app, you need to discover the bridge automatically using [Hue Bridge Discovery Guide](https://developers.meethue.com/develop/application-design-guidance/hue-bridge-discovery/).
    1. Go to the settings menu in the app. Go to Hue Bridges. Select your bridge. The ip address of the bridge will show.
    2. Use an mDNS discovery app to find Philips hue in your network.
    3. Use our broker server discover process by visiting [discovery.meethue.com](https://discovery.meethue.com)
    4. Log into your wireless router and look Philips hue up in the DHCP table.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://192.168.1.68'
    description: My Home Bridge
tags:
  - name: Auth
    description: Authentication operations.
  - name: Resource
    description: API to retrieve all API resources.
  - name: Light
    description: API to manage light services. These are offered by devices with lighting capabilities.
paths:
  /api:
    $ref: './auth/auth.yaml'
  /clip/v2/resource:
    $ref: './resource/resource.yaml'
  /clip/v2/resource/light:
    $ref: './light/light.yaml'
  /clip/v2/resource/light/{lightId}:
    $ref: './light/light_{lightId}.yaml'

components:
  securitySchemes:
    HueApplicationKey:
      type: apiKey
      in: header
      name: hue-application-key
