openapi: 3.0.3
info:
  title: Hue CLIP API
  version: v2
  description: See [openhue/openhue-api](https://github.com/openhue/openhue-api)
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://192.168.1.68'
    description: My Home Bridge
tags:
  - name: Auth
    description: Authentication operations.
  - name: Resource
    description: API to retrieve all API resources.
  - name: Light
    description: API to manage light services. These are offered by devices with lighting capabilities.
  - name: Bridge
    description: API to manage the bridge.
  - name: Bridge Home
    description: API to manage bridge homes. Homes group rooms as well as devices not assigned to a room.
  - name: Scene
    description: API to manage scenes. Scenes are used to store and recall settings for a group of lights.
  - name: Room
    description: API to manage rooms. Rooms group devices and each device can only be part of one room.
paths:
  /api:
    $ref: './auth/auth.yaml'
  /clip/v2/resource:
    $ref: './resource/resource.yaml'
  /clip/v2/resource/light:
    $ref: './light/light.yaml'
  /clip/v2/resource/light/{lightId}:
    $ref: './light/light_{lightId}.yaml'
  /clip/v2/resource/bridge:
    $ref: './bridge/bridge.yaml'
  /clip/v2/resource/bridge/{bridgeId}:
    $ref: './bridge/bridge_{bridgeId}.yaml'
  /clip/v2/resource/bridge_home:
    $ref: './bridge_home/bridge_home.yaml'
  /clip/v2/resource/bridge_home/{bridgeHomeId}:
    $ref: './bridge_home/bridge_home_{bridgeHomeId}.yaml'
  /clip/v2/resource/scene:
    $ref: './scene/scene.yaml'
  /clip/v2/resource/scene/{sceneId}:
    $ref: './scene/scene_{sceneId}.yaml'
  /clip/v2/resource/room:
    $ref: './room/room.yaml'
  /clip/v2/resource/room/{roomId}:
    $ref: './room/room_{roomId}.yaml'
components:
  securitySchemes:
    HueApplicationKey:
      type: apiKey
      in: header
      name: hue-application-key
