openapi: 3.0.3
info:
  title: Hue CLIP API
  version: v2
  description: See [thibauult/open-hue](https://github.com/thibauult/open-hue)
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://192.168.1.68'
    description: My Home Bridge
tags:
  - name: Auth
    description: Authentication operations.
  - name: Resource
    description: API to retrieve all API resources.
  - name: Light
    description: API to manage light services. These are offered by devices with lighting capabilities.
  - name: Bridge
    description: API to manage the bridge.
paths:
  /api:
    $ref: './auth/auth.yaml'
  /clip/v2/resource:
    $ref: './resource/resource.yaml'
  /clip/v2/resource/light:
    $ref: './light/light.yaml'
  /clip/v2/resource/light/{lightId}:
    $ref: './light/light_{lightId}.yaml'
  /clip/v2/resource/bridge:
    $ref: './bridge/bridge.yaml'
  /clip/v2/resource/bridge/{bridgeId}:
    $ref: './bridge/bridge_{bridgeId}.yaml'
components:
  securitySchemes:
    HueApplicationKey:
      type: apiKey
      in: header
      name: hue-application-key
