openapi: 3.0.3
info:
  title: Hue CLIP API
  version: v2
  description: See [openhue/openhue-api](https://github.com/openhue/openhue-api)
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://192.168.1.68'
    description: My Home Bridge
tags:
  - name: Auth
    description: Authentication operations.
  - name: Resource
    description: API to retrieve all API resources.
  - name: Light
    description: API to manage light services. These are offered by devices with lighting capabilities.
  - name: LightLevel
    description: API to manage light level services. These are offered by devices with light level sensing capabilities.
  - name: GroupedLight
    description: API to manage grouped light services. These are offered by rooms, zones, and homes.
  - name: Bridge
    description: API to manage the bridge.
  - name: Bridge Home
    description: API to manage bridge homes. Homes group rooms as well as devices not assigned to a room.
  - name: Scene
    description: API to manage scenes. Scenes are used to store and recall settings for a group of lights.
  - name: Room
    description: API to manage rooms. Rooms group devices and each device can only be part of one room.
  - name: Zone
    description: API to manage zones. Zones group services and each service can be part of multiple zones.
  - name: Temperature
    description: API to manage temperature services. These are offered by devices with temperature sensing capabilities.
paths:
#  Authentication
  /api:
    $ref: './auth/auth.yaml'
#  Resources
  /clip/v2/resource:
    $ref: './resource/resource.yaml'
#  Light
  /clip/v2/resource/light:
    $ref: './light/light.yaml'
  /clip/v2/resource/light/{lightId}:
    $ref: './light/light_{lightId}.yaml'
#  Light Level
  /clip/v2/resource/light_level:
    $ref: './light_level/light_level.yaml'
  /clip/v2/resource/light_level/{lightId}:
    $ref: './light_level/light_level_{lightLevelId}.yaml'
#  Grouped Level
  /clip/v2/resource/grouped_light:
    $ref: './grouped_light/grouped_light.yaml'
  /clip/v2/resource/grouped_light/{groupedLightId}:
    $ref: './grouped_light/grouped_light_{groupedLightId}.yaml'
#  Bridge
  /clip/v2/resource/bridge:
    $ref: './bridge/bridge.yaml'
  /clip/v2/resource/bridge/{bridgeId}:
    $ref: './bridge/bridge_{bridgeId}.yaml'
#  Bridge Home
  /clip/v2/resource/bridge_home:
    $ref: './bridge_home/bridge_home.yaml'
  /clip/v2/resource/bridge_home/{bridgeHomeId}:
    $ref: './bridge_home/bridge_home_{bridgeHomeId}.yaml'
#  Scene
  /clip/v2/resource/scene:
    $ref: './scene/scene.yaml'
  /clip/v2/resource/scene/{sceneId}:
    $ref: './scene/scene_{sceneId}.yaml'
#  Room
  /clip/v2/resource/room:
    $ref: './room/room.yaml'
  /clip/v2/resource/room/{roomId}:
    $ref: './room/room_{roomId}.yaml'
# Zone
  /clip/v2/resource/zone:
    $ref: './zone/zone.yaml'
  /clip/v2/resource/zone/{zoneId}:
    $ref: './zone/zone_{zoneId}.yaml'
# Temperature
  /clip/v2/resource/temperature:
    $ref: './temperature/temperature.yaml'
  /clip/v2/resource/temperature/{temperatureId}:
    $ref: './temperature/temperature_{temperatureId}.yaml'
components:
  securitySchemes:
    HueApplicationKey:
      type: apiKey
      in: header
      name: hue-application-key
